### ISSUE TITLE
Legge til kontaktinfo

### ISSUE THREAD

**Issue by plunun** [plunun/plunun.github.io#21]
Hei er det mulig å legge til linker e.l lignende til kontaktinfo, slik at man kan laste ned et visittkort? jeg har lagt til filer som inneholder min informasjon, men ikke Mariettes enda.

**Comment by SjoenH** [comment]
joda... Er det standardformat?
Altså vet du om det virker det på forskjellige operativsystem?

Skader ikke å prøve

**Comment by SjoenH** [comment]
I'm on it

**Comment by SjoenH** [comment]
VCF fungerte hos meg både på mac og android

**Comment by plunun** [comment]
Ser ut til å fungere på min mac i hvert fall ! bra!

**Comment by plunun** [comment]
så greit ut nå, blir d eventuelt tilpassa på fransk, eller komme d på norsk?

**Comment by plunun** [comment]
ja, d ser bra ut!
prøvde d på mariette sin tlf

**Comment by SjoenH** [comment]
Nice! :+1: :smiley: Så då rekne eg denna som ferdig :)
