### ISSUE TITLE
Fransk språk på meny

### ISSUE THREAD

**Issue by plunun** [plunun/plunun.github.io#24]
Jeg prøvde å endre menyen til fransk, men den ligger ikke inne med norske og franske klasser, er det mulig å fikse?

**Comment by SjoenH** [comment]
Ja, mulig å fikse, men kan hende at det er smartere å lage en ren norsk og en ren fransk side dersom alt skal være på to språk. 
Litt usikker på hva som er best.

**Comment by plunun** [comment]
Eventuelt å bare ta bort menylinjen

**Comment by SjoenH** [comment]
Menyen er vel mest praktisk å ha når du er på mobil... Trykke seg til hva du trenger fremfor å scrolle

**Comment by SjoenH** [comment]
Eg starte på #25

**Comment by SjoenH** [comment]
Da er det bare til å oversette menyen direkte i fransk.html :smiley:
