### ISSUE TITLE
Begge språk på en gang

### ISSUE THREAD

**Issue by plunun** [plunun/plunun.github.io#29]
Når man går inn på siden via domenet (hansmariette.tk) kommer begge språk på en gang, men det fikser seg om vi velger et av språkene etterpå
![capture](https://cloud.githubusercontent.com/assets/16616089/12293587/dbce27c0-b9f4-11e5-97bd-daacf30f9e8e.jpg)

**Comment by SjoenH** [comment]
Muligens en cache av den gamle index-siden

**Comment by plunun** [comment]
ok, ser ut til å være i ordne på imacen, får se på macbooken senere, men da er det sikkert bare det
